version: '3.8' # (recommended to always specify version)

services:
   postgres:
      image: postgres:latest
      container_name: postgres_container
      restart: always
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      ports:
         - '${POSTGRES_PORT:-5432}:5432'
      volumes:
         - postgres_data:/var/lib/postgresql/data

   app:
      container_name: ${APPNAME}
      build:
         context: .
         dockerfile: Dockerfile
      restart: always
      ports:
         - ${PORT}:3000
      depends_on:
         - postgres
      environment:
         - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
         - NODE_ENV=production
         - TZ=Europe/Stockholm
      volumes:
         - /var/lib/tailscale/certs:/certs:ro # remove if no https is needed

volumes:
   postgres_data:
