-- AlterTable
ALTER TABLE "User" ADD COLUMN     "flexSaldo" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "kompSaldo" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "semesterSaldo" INTEGER NOT NULL DEFAULT 0;
